version: '3.6'
services:
  cvxfin:
     build:
       context: .
       dockerfile: Dockerfile
       target: builder

     command: python d1.py

  jupyter:
    build:
      context: .
      dockerfile: binder/Dockerfile
    ports:
      - ${PORT}:8888
    volumes:
      - ./work:/home/${NB_USER}/work

  test:
    build:
       context: .
       dockerfile: Dockerfile
       target: test

    volumes:
      - ./cvxFin:/cvx/cvxFin:ro
      - ./test:/cvx/test:ro
      - ./artifacts:/cvx/artifacts
      - ./source:/source
      - ./helpers:/opt/.pycharm_helpers/pycharm:ro
