version: '2'
services:
  sut:
    build:
       context: .
       dockerfile: Dockerfile-Test
    command: nosetests --with-coverage --cover-html --cover-erase --cover-package=cvxFin --cover-html-dir=/cvxFin/html-coverage
    volumes:
     - ./html-coverage:/cvxFin/html-coverage
