version: '3.6'
services:
  sut:
    build:
       context: .
       dockerfile: Dockerfile
       target: test

    volumes:
      #- ./cvxFin:/cvx/cvxFin:ro
      - ./test:/cvx/test:ro
      - ./artifacts:/cvx/artifacts
      - ./source:/source:ro

