version: '3.6'
services:
  cvxfin:
     build:
       context: .
       dockerfile: Dockerfile
       target: builder

  jupyter:
    build:
      context: .
      dockerfile: binder/Dockerfile
    ports:
      - ${PORT}:8888
    volumes:
      - ./work:${WORK}
