version: '3.6'
services:
  test:
    build:
       context: .
       dockerfile: Dockerfile
       target: test

    volumes:
      - ./cvxFin:/cvx/cvxFin:ro
      - ./test:/cvx/test:ro
      - ./artifacts:/cvx/artifacts
      - ./source:/source
      - ./helpers:/opt/.pycharm_helpers/pycharm:ro
